### PR TITLE
Adding Tests to GeoPySpark

### PR DESCRIPTION
**Pull request by jbouffard**
This PR is branched from another current PR #16 .

Included in this PR are various unit tests for GeoPySpark. With these unit tests, various bug fixes and code clean up also occur.

### CODE REVIEW

**Comment by jamesmcclain** [comment]
Have any of these commits not yet been merged?

**Comment by jbouffard** [comment]
@jamesmcclain Most of those had been merged already, thanks for pointing that out.

**Comment by jamesmcclain** [comment]
No problem.

Would you mind rebasing this branch on top of the current master so that we can see what is what?

**Comment by jbouffard** [comment]
@jamesmcclain Just rebased. I also rebased this on top of another one of my PRs #16, so it should also have some commits from that branch as well.

**Comment by jamesmcclain** [comment]
It is also possible to force-push your rebased version of this branch into the PR branch.  That way we can keep PRs separate, but still make them readable.

**Comment by jbouffard** [comment]
@jamesmcclain This is ready for review.

**Pull request merged**
