### PR TITLE
Random CallbackServer port

### PR DESCRIPTION
**Pull request by echeipesh**
This is expedition for this fix from PR: https://github.com/jpolchlo/geopyspark/pull/5
which was made into GeoPySpark PR: https://github.com/locationtech-labs/geopyspark/pull/352
which was superseded by: https://github.com/locationtech-labs/geopyspark/pull/363
But this particular fix did not make the destination.

### CODE REVIEW

**Comment by jpolchlo** [comment]
I am filled with shame.

**Comment by jamesmcclain** [comment]
Wait, what?  What happened?

**Comment by jpolchlo** [comment]
The branch you modified was subsumed by a different branch, but your change was missed when the older branch was closed.  Oversight.

**Comment by jpolchlo** [comment]
I attempted testing with a notebook that has previously been verified to work(https://gist.github.com/jpolchlo/70798bac6a71235866841bda99c262cb).  The second example case ("Rendering with a custom Python function") yields errors of the form
```
py4j.Py4JException: Error while obtaining a new communication channel
	at py4j.CallbackClient.getConnectionLock(CallbackClient.java:218)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:337)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:316)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:103)
	at com.sun.proxy.$Proxy9.requiresEncoding(Unknown Source)
	at geopyspark.geotrellis.tms.TMSServerRoutes$RenderingTileRoute$$anonfun$root$1$$anonfun$apply$3$$anonfun$apply$4$$anonfun$apply$5.apply(TmsRoutes.scala:66)
	at geopyspark.geotrellis.tms.TMSServerRoutes$RenderingTileRoute$$anonfun$root$1$$anonfun$apply$3$$anonfun$apply$4$$anonfun$apply$5.apply(TmsRoutes.scala:65)
	at scala.Option.map(Option.scala:146)
	at geopyspark.geotrellis.tms.TMSServerRoutes$RenderingTileRoute$$anonfun$root$1$$anonfun$apply$3$$anonfun$apply$4.apply(TmsRoutes.scala:65)
	at geopyspark.geotrellis.tms.TMSServerRoutes$RenderingTileRoute$$anonfun$root$1$$anonfun$apply$3$$anonfun$apply$4.apply(TmsRoutes.scala:65)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277)
	at py4j.CallbackConnection.start(CallbackConnection.java:206)
	at py4j.CallbackClient.getConnection(CallbackClient.java:199)
	at py4j.CallbackClient.getConnectionLock(CallbackClient.java:211)
	... 20 more
```

**Comment by jpolchlo** [comment]
Have reached out to the Py4J mailing list (https://groups.google.com/a/py4j.org/forum/?utm_medium=email&utm_source=footer#!topic/py4j/zuDqBThUdKc).  The advertised solution for assigning a random port seems not to be working.  In fact, changing the port setting at all causes the callback sever to die.  Best guess is that we're setting the callback server parameters in the wrong place; most likely the JavaGateway needs the callback server parameters to be set upon creation.

**Comment by echeipesh** [comment]
I was able to verify this fix both locally on OSX and inside the docker container with A/B test.
A: calling `start_callback_server()`
B: calling `start_callback_server(callback_server_parameters=csp)` where `csp.port=0`

For docker I was using `quay.io/geodocker/jupyter-geopyspark:foss4g-2017-workshop` image
To test it I `pip3 uninstall geopyspark` and `pip3 install --user geopyspark.whl` after `docker cp`ing in into the container.

In both environments I saw failure in case A with exception below and success with case B:

exception in A
```
OSError                                   Traceback (most recent call last)
/usr/local/Cellar/apache-spark/2.2.0/libexec/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in start(self)
   2007         try:
-> 2008             self.server_socket.bind((self.address, self.port))
   2009             # 4-tuple for ipv6, 2-tuple for ipv4

OSError: [Errno 48] Address already in use

During handling of the above exception, another exception occurred:

Py4JNetworkError                          Traceback (most recent call last)
<ipython-input-4-585a339c262e> in <module>()
      1 nlcd_cmap = gps.ColorMap.nlcd_colormap()
----> 2 nlcd_tms_server = gps.TMS.build((catalog_uri, layer_name), nlcd_cmap)

~/proj/geopyspark/geopyspark/geotrellis/tms.py in build(cls, source, display)
    191 
    192         server = pysc._jvm.geopyspark.geotrellis.tms.TMSServer.createServer(route)
--> 193         return cls(server)

~/proj/geopyspark/geopyspark/geotrellis/tms.py in __init__(self, server)
    124         csp = copy.copy(self.pysc._gateway.callback_server_parameters)
    125         # csp.port = 0
--> 126         self.pysc._gateway.start_callback_server(callback_server_parameters=csp)
    127 
    128     def set_handshake(self, handshake):

/usr/local/Cellar/apache-spark/2.2.0/libexec/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in start_callback_server(self, callback_server_parameters)
   1704 
   1705         try:
-> 1706             self._callback_server.start()
   1707         except Py4JNetworkError:
   1708             # Clean up ourselves before raising the exception.

/usr/local/Cellar/apache-spark/2.2.0/libexec/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in start(self)
   2015                   "server ({0}:{1})".format(self.address, self.port)
   2016             logger.exception(msg)
-> 2017             raise Py4JNetworkError(msg, e)
   2018 
   2019         # Maybe thread needs to be cleanup up?

Py4JNetworkError: An error occurred while trying to start the callback server (127.0.0.1:25334)
```

**Pull request merged**
