### PR TITLE
docs spell check

### PR DESCRIPTION
**Pull request by rossbernet**

### CODE REVIEW

**Comment by yoninachmany** [comment]
cant suggest this edit currently, but it's related to spelling:

its able -> it is able/it's able
https://github.com/locationtech-labs/geopyspark/pull/242/files#diff-caf2a6b8f4947d018f68893c695b5202R9

**Comment by yoninachmany** [comment]
like ^, cant suggest edit:

It is this, "raw" data -> It is this "raw" data
https://github.com/locationtech-labs/geopyspark/pull/242/files#diff-604662d685272330c4a6a30c08ffafeeR174

**Comment by yoninachmany** [comment]
tuples. With -> tuples, with
https://github.com/locationtech-labs/geopyspark/pull/242/files#diff-604662d685272330c4a6a30c08ffafeeR181 & https://github.com/locationtech-labs/geopyspark/pull/242/files#diff-604662d685272330c4a6a30c08ffafeeR197

data. which -> data, which
https://github.com/locationtech-labs/geopyspark/pull/242/files#diff-604662d685272330c4a6a30c08ffafeeR191

**Comment by jbouffard** [comment]
@rossbernet There are conflicts with this PR. Could you please rebase on top of master and resolve the conflicts? @yoninachmany I think you should be able to make a PR against this PR with the spelling changes you'd like to make now. If you don't have time, though, then I can do it.

**Comment by yoninachmany** [comment]
hm - trying to create pr off of spelling pr, getting this back

screen shot 2017-06-08 at 11 18 05 am

**Pull request merged**
