### PR TITLE
Virtual Environment Installation

### LINKED ISSUE #182: Can't install geopyspark in a python virtualenv environment
Repro case:

- Make a [virtualenv](http://cheng.logdown.com/posts/2016/08/12/install-python3-and-virtualenv-on-mac):
```bash
mkvirtualenv --python=/usr/local/bin/python3 spark
```
- add the SPARK_HOME to virtualenv:
`vim ~/.envs/spark/bin/postactivate`
```bash
export SPARK_HOME=/usr/local/spark
```
- Activate virtualenv and install pygeospark
```bash
workon spark
git clone https://github.com/locationtech-labs/geopyspark.git
cd geopyspark
make install
```

You will get the following error message:

I get the following error:
```bash
python3 setup.py install --user --force --prefix=
running install
Checking .pth file support in /Users/rburhum/.local/lib/python3.6/site-packages/
/Users/rburhum/.virtualenvs/spark/bin/python3 -E -c pass
TEST FAILED: /Users/rburhum/.local/lib/python3.6/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Users/rburhum/.local/lib/python3.6/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/'

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
make: *** [install] Error 1
```

If I edit the Makefile like so:
```bash
rburhum@peru:~/geopyspark$ git diff
diff --git a/Makefile b/Makefile
index 6a884a8..fbc66f3 100644
--- a/Makefile
+++ b/Makefile
@@ -10,7 +10,7 @@ WHEEL := dist/${WHEELNAME}
 rwildcard=$(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2) $(filter $(subst *,%,$2),$d))

 install: ${DIST-ASSEMBLY} ${WHEEL}
-       ${PYTHON} setup.py install --user --force --prefix=
+       ${PYTHON} setup.py install

 ${DIST-ASSEMBLY}: ${BUILD-ASSEMBLY}
        cp -f ${BUILD-ASSEMBLY} ${DIST-ASSEMBLY}
rburhum@peru:~/geopyspark$
```
and to a `make install` it works fine.

### PR DESCRIPTION
**Pull request by jbouffard**
This PR makes it so that you can install GeoPySpark in a virtual environment.

This PR resolves #182

### CODE REVIEW

**Comment by jbouffard** [comment]
@echeipesh @jpolchlo @jamesmcclain Could one of you guys test this out when you get the chance?

How to install in a virtual environment (with [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/)):

1. mkvirtualenv geopyspark-test
2. mkdir geopyspark-test && cd geopyspark-test
3. git clone -b virtual-env https://github.com/jbouffard/geopyspark.git
4. cd geopyspark
5. make virtual-install

This should install GeoPySpark and all of its dependencies into the virtual environment

**Comment by jamesmcclain** [comment]
I had to type `PYTHONPATH=$HOME/.virtualenvs/geopyspark-test/lib/python3.4/site-packages make virtual-install` for the install to succeed.  It could just be user error on my part, but when I typed `make virtual-install`, it finished with the following error:
```
TEST FAILED: /home/likewise-open/AZVA-INT/jmcclain/.virtualenvs/geopyspark-test/lib/python3.4/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /home/likewise-open/AZVA-INT/jmcclain/.virtualenvs/geopyspark-test/lib/python3.4/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
make: *** [virtual-install] Error 1
```

**Comment by jbouffard** [comment]
@jamesmcclain Thank you for testing it out. What's weird about your error is that in the `virtual-install` command, `--prefix` is set, so `PYTHONPATH` should have been ignored. In fact, the `PYTHONPATH` you had to set is identical to where the the installation should have been installed to by default. Since `VIRTUAL_ENV` is `/home/likewise-open/AZVA-INT/jmcclain/.virtualenvs/geopyspark-test/` and `lib/python3.4/site-packages` should have been appended to it during the install.

**Comment by jpolchlo** [comment]
I had no trouble following your instructions. My PYTHONPATH variable is unset.  I verified by starting python and typing `import geopyspark`.

**Comment by jamesmcclain** [comment]
I probably just setup `virtualenvwrapper` incorrectly.  I have no objections to this PR.

**Comment by jbouffard** [comment]
Okay. Once @rossbernet tests this PR out and has no trouble with it I'll merge this then. Thank you both for taking the time to try this out.

**Pull request merged**
